-- Local H2 schema for library management

CREATE TABLE IF NOT EXISTS doc_gia (
    doc_gia_id VARCHAR(50) PRIMARY KEY,
    ten_doc_gia VARCHAR(200) NOT NULL,
    so_dien_thoai VARCHAR(20),
    email VARCHAR(100),
    dia_chi TEXT,
    loai_doc_gia VARCHAR(50),
    tong_tien_muon DECIMAL(15,2) DEFAULT 0,
    so_lan_muon INTEGER DEFAULT 0,
    tong_tien_phat DECIMAL(15,2) DEFAULT 0,
    diem_tich_luy INTEGER DEFAULT 0,
    ngay_tham_gia DATE DEFAULT CURRENT_DATE,
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tai_lieu (
    tai_lieu_id VARCHAR(50) PRIMARY KEY,
    ten_tai_lieu VARCHAR(200) NOT NULL,
    so_luong_ton INTEGER NOT NULL DEFAULT 0,
    tac_gia VARCHAR(200),
    nha_xuat_ban VARCHAR(200),
    nam_xuat_ban INTEGER,
    ngay_nhap TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gia_nhap DECIMAL(15,2),
    the_loai VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS muon_tra (
    muon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_phieu_muon VARCHAR(50),
    tai_lieu_id VARCHAR(50) NOT NULL,
    ten_tai_lieu VARCHAR(200) NOT NULL,
    ten_doc_gia VARCHAR(200),
    doc_gia VARCHAR(200),
    ngay_muon TIMESTAMP NOT NULL,
    ghi_chu VARCHAR(500),
    gia_muon DECIMAL(15,2) NOT NULL,
    so_luong_muon INTEGER NOT NULL,
    tong_tien DECIMAL(15,2),
    gia_nhap DECIMAL(15,2),
    CONSTRAINT fk_muon_tai_lieu FOREIGN KEY (tai_lieu_id) REFERENCES tai_lieu(tai_lieu_id)
);

CREATE TABLE IF NOT EXISTS nhap_tai_lieu (
    nhap_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tai_lieu_id VARCHAR(50) NOT NULL,
    ten_tai_lieu VARCHAR(200) NOT NULL,
    so_luong_nhap INTEGER NOT NULL,
    gia_nhap DECIMAL(15,2) NOT NULL,
    ngay_nhap TIMESTAMP NOT NULL,
    nha_cung_cap VARCHAR(200),
    nguoi_nhap VARCHAR(100),
    ghi_chu VARCHAR(500),
    trang_thai VARCHAR(50),
    ma_phieu_nhap VARCHAR(50),
    CONSTRAINT fk_nhap_tai_lieu FOREIGN KEY (tai_lieu_id) REFERENCES tai_lieu(tai_lieu_id)
);

CREATE INDEX IF NOT EXISTS idx_tai_lieu_the_loai ON tai_lieu(the_loai);
CREATE INDEX IF NOT EXISTS idx_muon_tra_doc_gia ON muon_tra(ten_doc_gia);
CREATE INDEX IF NOT EXISTS idx_muon_tra_ngay_muon ON muon_tra(ngay_muon);
