-- Local H2 schema for library management

CREATE TABLE IF NOT EXISTS doc_gia (
    doc_gia_id VARCHAR(50) PRIMARY KEY,
    ten_doc_gia VARCHAR(200) NOT NULL,
    so_dien_thoai VARCHAR(20),
    email VARCHAR(100),
    dia_chi TEXT,
    loai_doc_gia VARCHAR(50),
    tai_khoan VARCHAR(100),
    mat_khau VARCHAR(255),
    quyen_han VARCHAR(50),
    tong_tien_muon DECIMAL(15,2) DEFAULT 0,
    so_lan_muon INTEGER DEFAULT 0,
    tong_tien_phat DECIMAL(15,2) DEFAULT 0,
    diem_tich_luy INTEGER DEFAULT 0,
    ngay_tham_gia DATE DEFAULT CURRENT_DATE,
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tai_lieu (
    tai_lieu_id VARCHAR(50) PRIMARY KEY,
    ten_tai_lieu VARCHAR(200) NOT NULL,
    so_luong_ton INTEGER NOT NULL DEFAULT 0,
    tac_gia VARCHAR(200),
    nha_xuat_ban VARCHAR(200),
    nam_xuat_ban INTEGER,
    ngay_nhap TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gia_nhap DECIMAL(15,2),
    the_loai VARCHAR(100),
    vi_tri VARCHAR(100)
);

ALTER TABLE tai_lieu ADD COLUMN IF NOT EXISTS vi_tri VARCHAR(100);

CREATE TABLE IF NOT EXISTS muon_tra (
    muon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_phieu_muon VARCHAR(50),
    tai_lieu_id VARCHAR(50) NOT NULL,
    ten_tai_lieu VARCHAR(200) NOT NULL,
    ten_doc_gia VARCHAR(200),
    doc_gia VARCHAR(200),
    ngay_muon TIMESTAMP NOT NULL,
    ngay_hen_tra TIMESTAMP,
    ngay_tra TIMESTAMP,
    trang_thai VARCHAR(50),
    so_ngay_gia_han INTEGER,
    ghi_chu VARCHAR(500),
    gia_muon DECIMAL(15,2) NOT NULL,
    so_luong_muon INTEGER NOT NULL,
    tong_tien DECIMAL(15,2),
    gia_nhap DECIMAL(15,2),
    CONSTRAINT fk_muon_tai_lieu FOREIGN KEY (tai_lieu_id) REFERENCES tai_lieu(tai_lieu_id)
);

ALTER TABLE muon_tra ADD COLUMN IF NOT EXISTS ngay_hen_tra TIMESTAMP;
ALTER TABLE muon_tra ADD COLUMN IF NOT EXISTS ngay_tra TIMESTAMP;
ALTER TABLE muon_tra ADD COLUMN IF NOT EXISTS trang_thai VARCHAR(50);
ALTER TABLE muon_tra ADD COLUMN IF NOT EXISTS so_ngay_gia_han INTEGER;

CREATE TABLE IF NOT EXISTS nhap_tai_lieu (
    nhap_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tai_lieu_id VARCHAR(50) NOT NULL,
    ten_tai_lieu VARCHAR(200) NOT NULL,
    so_luong_nhap INTEGER NOT NULL,
    gia_nhap DECIMAL(15,2) NOT NULL,
    ngay_nhap TIMESTAMP NOT NULL,
    nha_cung_cap VARCHAR(200),
    nguoi_nhap VARCHAR(100),
    ghi_chu VARCHAR(500),
    trang_thai VARCHAR(50),
    ma_phieu_nhap VARCHAR(50),
    CONSTRAINT fk_nhap_tai_lieu FOREIGN KEY (tai_lieu_id) REFERENCES tai_lieu(tai_lieu_id)
);

CREATE INDEX IF NOT EXISTS idx_tai_lieu_the_loai ON tai_lieu(the_loai);
CREATE INDEX IF NOT EXISTS idx_muon_tra_doc_gia ON muon_tra(ten_doc_gia);
CREATE INDEX IF NOT EXISTS idx_muon_tra_ngay_muon ON muon_tra(ngay_muon);

CREATE TABLE IF NOT EXISTS dat_phong (
    dat_phong_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_dat_phong VARCHAR(50),
    ma_phong VARCHAR(50) NOT NULL,
    ten_phong VARCHAR(200) NOT NULL,
    ten_nguoi_dat VARCHAR(200) NOT NULL,
    ma_nguoi_dat VARCHAR(50),
    loai_nguoi_dat VARCHAR(50),
    muc_dich VARCHAR(300),
    so_luong_nguoi INTEGER,
    thoi_gian_bat_dau TIMESTAMP,
    thoi_gian_ket_thuc TIMESTAMP,
    trang_thai VARCHAR(50),
    ghi_chu VARCHAR(500),
    so_lan_gia_han INTEGER
);

CREATE TABLE IF NOT EXISTS lich_trong_phong (
    lich_trong_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_phong VARCHAR(50) NOT NULL,
    ten_phong VARCHAR(200) NOT NULL,
    bat_dau TIMESTAMP NOT NULL,
    ket_thuc TIMESTAMP NOT NULL,
    ghi_chu VARCHAR(500),
    trang_thai VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS vi_pham_phong (
    vi_pham_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_bien_lai VARCHAR(50),
    ma_doc_gia VARCHAR(50) NOT NULL,
    ten_doc_gia VARCHAR(200) NOT NULL,
    ma_tai_lieu VARCHAR(50),
    ten_tai_lieu VARCHAR(200),
    loai_vi_pham VARCHAR(50) NOT NULL,
    so_ngay_qua_han INTEGER,
    so_luong INTEGER,
    so_tien_den_bu DECIMAL(15,2),
    so_tien_phat DECIMAL(15,2),
    tong_tien DECIMAL(15,2),
    ghi_chu VARCHAR(500),
    ngay_ghi_nhan TIMESTAMP
);

CREATE TABLE IF NOT EXISTS thong_bao_mau (
    thong_bao_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_mau VARCHAR(50),
    loai_thong_bao VARCHAR(100) NOT NULL,
    tieu_de VARCHAR(200) NOT NULL,
    noi_dung TEXT NOT NULL,
    doi_tuong VARCHAR(100),
    kenh_gui VARCHAR(100),
    trang_thai VARCHAR(50),
    ngay_gui TIMESTAMP,
    ngay_tao TIMESTAMP,
    ngay_cap_nhat TIMESTAMP
);

ALTER TABLE dat_phong ADD COLUMN IF NOT EXISTS so_lan_gia_han INTEGER;
ALTER TABLE doc_gia ADD COLUMN IF NOT EXISTS tai_khoan VARCHAR(100);
ALTER TABLE doc_gia ADD COLUMN IF NOT EXISTS mat_khau VARCHAR(255);
ALTER TABLE doc_gia ADD COLUMN IF NOT EXISTS quyen_han VARCHAR(50);
